interface REPORT_CATEGORY_TYPE {
  [key: string]: string;
}

export const REPORT_CATEGORY: REPORT_CATEGORY_TYPE = {
  PROHIBITED_GOODS: '판매금지 물품이에요',
  USED_TRANSACTION_POST: '중고 거래 게시글이 아니에요',
  PROFESSIONAL_VENDOR: '전문 판매업자 같아요',
  FRAUDULENT_WRITING: '사기 글이에요',
  TRANSACTION_AND_REFUND_DISPUTE: '거래/환불 분쟁',
  OTHER_REASONS: '기타 사유 선택'
};
export const REPORT_CATEGORY_LIST = [
  'PROHIBITED_GOODS',
  'USED_TRANSACTION_POST',
  'PROFESSIONAL_VENDOR',
  'FRAUDULENT_WRITING',
  'TRANSACTION_AND_REFUND_DISPUTE',
  'OTHER_REASONS'
];
